### ISSUE TITLE
Package is removing spaces from strings

### ISSUE THREAD

**Issue by vanth0me** [LaTrita97/localized_rich_text#2]
Hello,

I have been using your package for an easier way to have localized strings with variables. The only problem I encountered is that the package is removing spaces at the end of the character, and then I have to add them back in the replaced string, only that in some cases this produces unwanted behavior in other languages, because of different placement of variables.

I saw in your source code that you are trimming the left of the variable. Is this really necessary? Or maybe give an option to enable or disable this.

Hope to hear from you soon.

**Comment by vanth0me** [comment]
Hi, I think any string works with spaces after a variable. For example "I am a #platform mobile developer" where only #platform is interchangeable. It trimmed the " " after #platform making the scentence "I am a fluttermobile developer".

Thanks for your quick response and I'm looking forward to your solution.

**Comment by LaTrita97** [comment]
Hi, @vanth0me I fixed the problem and now it should be working.
Let me know if you have any problems.

**Comment by vanth0me** [comment]
I tried your new version and it works as expected. Thanks for the quick fix and sorry for the late response.
