### ISSUE TITLE
SDK constraints

### ISSUE THREAD

**Issue by th8m0z** [LaTrita97/localized_rich_text#3]
Is it possible to lower the SDK constraints for those who are still using Flutter 2.5?

**Comment by LaTrita97** [comment]
At this moment is not possible, I'm sorry.

I suggest you go on the source code of this repository and copy and paste into your project the files `lib/extensions.dart` and `lib/localized_rich_text.dart`.

The code is very simple and you can use it also on the web.

I hope to have helped you.
