### ISSUE TITLE
Update Kotlin version

### ISSUE THREAD

**Issue by AtamyratBabayev** [LaTrita97/localized_rich_text#5]
## Motivation
In case to use this library with latest Gradle version Kotlin version should be updated at least to version [1.5.20].

## The way I see it
Update Kotlin version in path: [<app-src>/android/build.gradle]. Get more info here: [link](https://docs.flutter.dev/release/breaking-changes/kotlin-version).

## Todo
 - [x] Update min Sdk version.
 - [x] Update kotlin version to [1.5.31]

**Comment by LaTrita97** [comment]
Hi @AtamyratBabayev I've just deployed a [newer version](https://pub.dev/packages/localized_rich_text) with the bug fixed.
Thanks for the issue opened, I didn't notice that problem!
